name: Synchronize to forked server repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FORKED_REPO_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://kimwonjuun:${{ secrets.FORKED_REPO_TOKEN }}@github.com/kimwonjuun/WooyeonBook_Server
          git config user.name kimwonjuun
          git config user.email https://github.com/kimwonjuun

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
